### ISSUE TITLE
Error while training pose refiner.

### ISSUE THREAD

**Issue by vikas-baghel** [yshah43/DPOD#3]
I executed the train.py file. Training of correspondence block ran smoothly, but during training of pose refiner I am getting this error-
```
------ Started Initial pose estimation ------
0/2370 finished!
1000/2370 finished!
2000/2370 finished!
Number of instances where PnP couldn't be used:  352
------ Finished Initial pose estimation -----
----- Started creating inputs for DL based pose refinement ------
0/2370 finished!
/content/DPOD/create_renderings.py:31: RuntimeWarning: overflow encountered in true_divide
  coord_2D = homogenous_2D[:2, :] / homogenous_2D[2, :]
1000/2370 finished!
2000/2370 finished!
Number of outliers:  29
----- Finished creating inputs for DL based pose refinement
----- Started training DL based pose refiner ------
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/checkpoints/resnet18-5c106cde.pth
100% 44.7M/44.7M [00:00<00:00, 309MB/s]
----- Epoch Number:  1 --------
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    train_pose_refinement(root_dir, classes, epochs=10)
  File "/content/DPOD/pose_refinement.py", line 147, in train_pose_refinement
    xy, z, rot = pose_refiner(image, rendered, pred_pose, batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/DPOD/pose_refiner_architecture.py", line 63, in forward
    z = self.fc_zhead(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [4 x 256], m2: [512 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:283
```
I didn't made any changes in the code. Can you please help me with this error.

**Comment by yshah43** [comment]
I never got this error before. Do you mind training the pose refiner block again?
You can comment out the all lines before 76 to check if its trains properly

**Comment by vikas-baghel** [comment]
I trained it again but I am facing the same issue. Btw I am using google collab. Does it have to do something with the error?

**Comment by yshah43** [comment]
I can't speak for colab but I used [Deepnote](https://deepnote.com). You can get a free gpu by requesting one
